
name: latestag

# manully trigger the job 

on:
  push:


jobs:  
 latestag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: store tag
        run: echo "GIT_TAG=`echo $(git describe --tags --abbrev=0)`" >> $GITHUB_ENV

      - name: display leatet tag
        run: echo "${{ env.GIT_TAG }}"
