
name: latestag

# manully trigger the job 

on:
  push:


jobs:  
 job1:
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.step1.outputs.test }}
    steps:
      - uses: actions/checkout@v2
      - id: step1
        run: echo "::set-output name=test::hello sir"

      # - name: store tag
      #   run: echo "::set-output name=test::hello"
      #   echo "GIT_TAG=hello sir" >> $GITHUB_ENV
  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - uses: actions/checkout@v2
      - name: display the output
        run: echo ${{needs.job1.outputs.output1}}
