name: prod-CI 

# manully trigger the job 

on:
  workflow_dispatch:
    inputs:
      image-tag:
        description: 'enter image tag'     
        required: true
        default: 'v2.0.1'

  workflow_run:
    workflows: ["Tagging"]
    types:
      - completed        
  push:
    tags:        
      - v*
      - V*



jobs:
 prod-CI:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'

      - name: display leatet tag
        run: git describe --tags --abbrev=0


      - name: display all environmental varaibles
        shell: "bash"
        run: |-
          if [[ ${{ github.event_name }} == workflow_run && ${{ github.ref_name }} == master && ${{ github.ref_type }} == branch ]]; then echo "IMAGE_TAG=$(git describe --tags --abbrev=0)" >> $GITHUB_ENV; fi


      - name: display all environmental varaibles
        run: |
          echo "${{ env.IMAGE_TAG }}"
          echo ${{ github.ref_type }} 
          echo ${{ github.ref_name }}
          echo ${{ github.event }}
          echo ${{ github.event_name }}
          echo "${{ github.run_id }}"
          echo "{{ github.run_number }}"
          echo "$GITHUB_RUN_NUMBER"echo "${{ github.server_url }}/${{ github.repository }}"
          echo ${{ env.URL_GITACTION }}
          echo ${GITHUB_REF##*/}
          echo ${{ github.actor }} 
          echo ${{ github.action_path }}
          echo ${{ github.action_ref }}
          echo ${{ github.action_repository	}}
          echo ${{ github.actor }}
          echo ${{ github.api_url }}
          echo ${{ github.base_ref }}
          echo ${{ github.env }}
          echo ${{ github.event }}
          echo ${{ github.event_name }}
          echo ${{ github.event_path }}
          echo ${{ github.graphql_url }}
          echo ${{ github.head_ref }}
          echo ${{ github.job }}
          echo ${{ github.ref }}
          echo ${{ github.ref_protected }}
          echo ${{ github.path	 }}
          echo ${{ github.repository }}
          echo ${{ github.repository_owner }}
          echo ${{ github.repositoryUrl }}
          echo ${{ github.retention_days }}
          echo ${{ github.run_id }}
          echo ${{ github.run_number }}
          echo ${{ github.run_attempt }}
          echo ${{ github.server_url }}
          echo ${{ github.sha }}
          echo ${{ github.token }}
          echo ${{ github.workflow }}
          echo ${{ github.workspace }}
          echo ${{github.event.head_commit.message}} 
        
