name: Merge-Master-to-Feature
on:
  push:
    branches:    
      - '**'        # matches every branch
jobs:
  Merge-Master-to-Feature:
    runs-on: ubuntu-latest 
    steps:
#fetch the code     
      - uses: actions/checkout@v2

      - name: Who started this workflow
        run: echo "This workflow is started by ${{ github.actor }}" 
    
      - name: Store shell script 
        shell: bash
        run: |-
          cd ..
          echo "storing shell script path"
          echo "SHELL_PATH=$(pwd)" >> $GITHUB_ENV
          cat << EoF > auto-merge-from-master-to-feature.sh
          Hello world
          Have a nice day
          EoF

      - name: Store shell script 
        shell: bash
        run: |-
          cd ..
          cat auto-merge-from-master-to-feature.sh     
