name: Merge-Master-to-Feature
on:
  push:
    branches:    
      - '**'        # matches every branch
jobs:
  Merge-Master-to-Feature:
    runs-on: ubuntu-latest 
    steps:
#fetch the code     
      - uses: actions/checkout@v2

      - name: Who started this workflow
        run: echo "This workflow is started by ${{ github.actor }}" 
    
      - name: Store shell script 
        shell: bash
        run: |-
          cd ..
          echo "storing shell script path"
          echo "SHELL_PATH=$(pwd)" >> $GITHUB_ENV
          cat >> auto-merge-from-master-to-feature.sh <<HERE
          Hello world HERE <-- Not by itself on a separate line -> not considered end of string
          This is a test
          HERE <-- Leading space, so not considered end of string
          and a new line
          HERE <-- Now we h

      - name: Store shell script 
        shell: bash
        run: |-
          cd ..
          cat auto-merge-from-master-to-feature.sh     
